"use client";

import type { CSSProperties } from "react";
import { useEffect, useMemo, useRef, useState } from "react";

import type {
  TemplateSectionInstance,
  ThemeManifestDefinition,
  ThemeSettingsRecord,
} from "../../types";
import { evaluateThemeCssVars } from "../../utilities/evaluateThemeCssVars";
import { subscribeThemeLivePreview } from "./subscribe";

export interface UseThemeLivePreviewOptions {
  applyToRoot?: boolean;
  baseTokens?: Record<string, string>;
  initialSections?: TemplateSectionInstance[];
  initialSettings?: ThemeSettingsRecord;
  initialTemplate?: { sections?: TemplateSectionInstance[] | null } | null;
  initialTheme?: { settings?: ThemeSettingsRecord | null } | null;
  manifest: ThemeManifestDefinition;
  serverURL?: string;
}

export interface UseThemeLivePreviewResult {
  isLive: boolean;
  sections: TemplateSectionInstance[];
  settings: ThemeSettingsRecord;
  style: CSSProperties;
  themeCssVars: Record<string, string>;
}

interface LivePreviewState {
  sections: TemplateSectionInstance[];
  settings: ThemeSettingsRecord;
  themeCssVars: Record<string, string>;
}

export const useThemeLivePreview = ({
  applyToRoot = true,
  baseTokens,
  initialSections,
  initialSettings,
  initialTemplate,
  initialTheme,
  manifest,
  serverURL,
}: UseThemeLivePreviewOptions): UseThemeLivePreviewResult => {
  const resolvedInitialSettings = useMemo(() => {
    if (initialSettings) {
      return initialSettings;
    }

    const themeSettings = initialTheme?.settings;
    if (themeSettings && typeof themeSettings === "object") {
      // SAFETY: Validated themeSettings is a non-null object matching ThemeSettingsRecord.
      return themeSettings as ThemeSettingsRecord;
    }

    return {};
  }, [initialSettings, initialTheme]);

  const resolvedInitialSections = useMemo(() => {
    if (initialSections) {
      return initialSections;
    }

    const templateSections = initialTemplate?.sections;
    if (Array.isArray(templateSections)) {
      return templateSections;
    }

    return [];
  }, [initialSections, initialTemplate]);

  const initialThemeCssVars = useMemo(
    () =>
      evaluateThemeCssVars({
        baseTokens,
        manifest,
        settings: resolvedInitialSettings,
      }),
    [baseTokens, manifest, resolvedInitialSettings]
  );

  const [liveData, setLiveData] = useState<LivePreviewState | null>(null);

  const initialSectionsRef = useRef(resolvedInitialSections);
  const initialSettingsRef = useRef(resolvedInitialSettings);

  useEffect(() => {
    initialSectionsRef.current = resolvedInitialSections;
    initialSettingsRef.current = resolvedInitialSettings;
  }, [resolvedInitialSections, resolvedInitialSettings]);

  useEffect(() => {
    const unsubscribe = subscribeThemeLivePreview({
      applyToRoot,
      baseTokens,
      initialSections: initialSectionsRef.current,
      initialSettings: initialSettingsRef.current,
      manifest,
      serverURL,
      onUpdate: (update) => {
        setLiveData({
          sections: update.sections,
          settings: update.settings,
          themeCssVars: update.themeCssVars,
        });
      },
    });

    return unsubscribe;
  }, [applyToRoot, baseTokens, manifest, serverURL]);

  const isLive = liveData !== null;
  const sections = liveData ? liveData.sections : resolvedInitialSections;
  const settings = liveData ? liveData.settings : resolvedInitialSettings;
  const themeCssVars = liveData ? liveData.themeCssVars : initialThemeCssVars;

  // SAFETY: CSS custom properties generated by evaluateThemeCssVars are valid CSSProperties dictionary.
  const style = themeCssVars as CSSProperties;

  return {
    isLive,
    sections,
    settings,
    style,
    themeCssVars,
  };
};
