/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    categories: Category;
    packages: Package;
    products: Product;
    media: Media;
    variants: Variant;
    variantOptions: VariantOption;
    variantTypes: VariantType;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    products: {
      variants: 'variants';
    };
    variantTypes: {
      options: 'variantOptions';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  username?: string | null;
  password?: string | null;
  roles?: ('super-admin' | 'user')[] | null;
  tenants?:
    | {
        tenant: number | Tenant;
        roles: ('owner' | 'manager')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * Display name of the merchant's store
   */
  name: string;
  /**
   * Subdomain identifier (e.g. {slug}.omsetdigital.com)
   */
  slug: string;
  /**
   * Buyer-facing custom domain (e.g. myshop.com)
   */
  customDomain?: string | null;
  /**
   * Active storefront theme
   */
  theme: 'default' | 'minimal';
  /**
   * Accent colors, fonts, and per-theme overrides
   */
  themeConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  subscription: {
    status: 'trial' | 'active' | 'past_due' | 'canceled';
    trialEndsAt?: string | null;
    currentPeriodEnd?: string | null;
  };
  /**
   * Active payment gateway. Add one block and fill in your credentials.
   */
  paymentProviders?:
    | {
        secretKey?: string | null;
        /**
         * Callback token from Xendit Dashboard → Webhooks settings
         */
        webhookToken?: string | null;
        mode: 'test' | 'live';
        id?: string | null;
        blockName?: string | null;
        blockType: 'xendit';
      }[]
    | null;
  /**
   * Shipping provider credentials and origin configuration
   */
  shippingConfig?: {
    /**
     * Active shipping provider
     */
    shippingProvider?: ('none' | 'rajaongkir') | null;
    rajaongkirConfig?: {
      /**
       * Restricted to tenant owner and super-admin
       */
      apiKey?: string | null;
      accountType?: ('starter' | 'basic' | 'pro') | null;
      /**
       * Origin city for shipping cost calculation
       */
      originCityId?: string | null;
      /**
       * Only applicable for Pro account type
       */
      originSubdistrictId?: string | null;
    };
  };
  whatsappConfig?: {
    enabled?: boolean | null;
    phoneNumber?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug?: string | null;
  slugLock?: boolean | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  dimensions: {
    length: number;
    width: number;
    height: number;
  };
  tareWeight: {
    value: number;
    unit: 'g' | 'kg';
  };
  /**
   * Used to calculate rates at checkout and pre-selected when buying labels
   */
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  media?:
    | {
        asset: number | Media;
        id?: string | null;
      }[]
    | null;
  pricing?: {
    price: number;
    /**
     * Enter a value higher than your price. Often shown with a strikethrough (e.g., $25.00).
     */
    compareAtPrice?: number | null;
  };
  inventory?: {
    tracked?: boolean | null;
    /**
     * Available inventory.
     */
    stock?: number | null;
    sku?: string | null;
    barcode?: string | null;
    allowBackorder?: boolean | null;
  };
  shipping?: {
    required?: boolean | null;
    package: number | Package;
    weight: {
      value: number;
      unit: 'g' | 'kg';
    };
  };
  variantTypes?: (number | VariantType)[] | null;
  variants?: {
    docs?: (number | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  category?: (number | null) | Category;
  relatedProducts?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: number;
  tenant?: (number | null) | Tenant;
  label: string;
  name: string;
  options?: {
    docs?: (number | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: number;
  _variantOptions_options_order?: string | null;
  tenant?: (number | null) | Tenant;
  variantType: number | VariantType;
  label: string;
  /**
   * Machine-readable value, such as "small" or "red".
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Generated administrative title, such as Small / Red.
   */
  title?: string | null;
  /**
   * Featured image for this variant. Automatically synced to product gallery.
   */
  image?: (number | null) | Media;
  options?: (number | VariantOption)[] | null;
  pricing: {
    price: number;
    /**
     * Enter a value higher than your price. Often shown with a strikethrough (e.g., $25.00).
     */
    compareAtPrice?: number | null;
  };
  inventory?: {
    tracked?: boolean | null;
    /**
     * Available inventory.
     */
    stock?: number | null;
    sku?: string | null;
    barcode?: string | null;
    allowBackorder?: boolean | null;
  };
  shipping: {
    required?: boolean | null;
    package: number | Package;
    weight: {
      value: number;
      unit: 'g' | 'kg';
    };
  };
  product: number | Product;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: number | VariantOption;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: number | VariantType;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  password?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  customDomain?: T;
  theme?: T;
  themeConfig?: T;
  subscription?:
    | T
    | {
        status?: T;
        trialEndsAt?: T;
        currentPeriodEnd?: T;
      };
  paymentProviders?:
    | T
    | {
        xendit?:
          | T
          | {
              secretKey?: T;
              webhookToken?: T;
              mode?: T;
              id?: T;
              blockName?: T;
            };
      };
  shippingConfig?:
    | T
    | {
        shippingProvider?: T;
        rajaongkirConfig?:
          | T
          | {
              apiKey?: T;
              accountType?: T;
              originCityId?: T;
              originSubdistrictId?: T;
            };
      };
  whatsappConfig?:
    | T
    | {
        enabled?: T;
        phoneNumber?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  slugLock?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  dimensions?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
      };
  tareWeight?:
    | T
    | {
        value?: T;
        unit?: T;
      };
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  description?: T;
  media?:
    | T
    | {
        asset?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        price?: T;
        compareAtPrice?: T;
      };
  inventory?:
    | T
    | {
        tracked?: T;
        stock?: T;
        sku?: T;
        barcode?: T;
        allowBackorder?: T;
      };
  shipping?:
    | T
    | {
        required?: T;
        package?: T;
        weight?:
          | T
          | {
              value?: T;
              unit?: T;
            };
      };
  variantTypes?: T;
  variants?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  generateSlug?: T;
  slug?: T;
  category?: T;
  relatedProducts?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  image?: T;
  options?: T;
  pricing?:
    | T
    | {
        price?: T;
        compareAtPrice?: T;
      };
  inventory?:
    | T
    | {
        tracked?: T;
        stock?: T;
        sku?: T;
        barcode?: T;
        allowBackorder?: T;
      };
  shipping?:
    | T
    | {
        required?: T;
        package?: T;
        weight?:
          | T
          | {
              value?: T;
              unit?: T;
            };
      };
  product?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  tenant?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  tenant?: T;
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}